export const GET_DATA = 'GET_DATA';
export const CLEAR_DATA = 'CLEAR_DATA';
export const LOADING_DATA = 'LOADING_DATA';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';
export const TYPE_VIEW_TABLE = 'TYPE_VIEW_TABLE';
export const SET_SEARCH_PARAMS = 'SET_SEARCH_PARAMS';
export const GET_DESCRIPTION = 'GET_DESCRIPTION';
